export const POPULAR_ACTON = "FETCH_MOVIES_POUPULAR_";
export const TRENDING_ACTON = "FETCH_MOVIES_TRENDING_";
export const SET_LOADING = "SET_LOADING";
export const SET_MOVIES_NAME = "SET_MOVIES_NAME";
